version: '3.8'

services:
  # 后端服务
  backend:
    image: ghcr.io/fyerfyer/k8s-app:latest
    container_name: k8s-backend
    restart: unless-stopped
    ports:
      - "8081:8081"
    environment:
      - TZ=Asia/Shanghai
      # 可以通过环境变量指定KUBECONFIG路径
      - KUBECONFIG=/root/.kube/config
    volumes:
      # 挂载本地kubeconfig到容器内
      - ${HOME}/.kube:/root/.kube:ro
    networks:
      - k8s-network
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://localhost:8081/ping"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 256M

  # 前端服务
  frontend:
    image: ghcr.io/fyerfyer/vue-frontend:latest
    container_name: k8s-frontend
    restart: unless-stopped
    # 为防止端口重复，将80端口映射到8080端口
    ports:
      - "8080:80"
    depends_on:
      - backend
    environment:
      - TZ=Asia/Shanghai
    networks:
      - k8s-network
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://localhost:80/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s
    deploy:
      resources:
        limits:
          cpus: '0.3'
          memory: 128M

networks:
  k8s-network:
    driver: bridge